#-------------------------------
# General Site Settings

title: しろくま＠胡瓜's Blog
description: 中部地方に住むしろくま＠胡瓜の雑談的なブログです。
baseurl: ""
url: "https://shirokuma-89.github.io"

#-------------------------------
# About Section
author-name:   しろくま＠胡瓜
author-avatar: user-icon.png


#-------------------------------
# Contact links
qiita:  https://qiita.com/Shirokuma89
twitter:   https://twitter.com/robokichi41 # Add your Facebook handle
github:   https://github.com/shirokuma-89


# #-------------------------------
# # Comment Section (Disqus)
# disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# gems:
#   - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

future: false

sass:
  sass_dir: _sass
  style: compressed

timezone: Asia/Tokyo


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
